# Generated by Django 3.1.7 on 2021-03-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='add',
            new_name='ad',
        ),
    ]
