# Generated by Django 3.1.7 on 2021-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210306_1743'),
        ('ad', '0003_auto_20210306_1849'),
        ('meter', '0002_meter_created'),
        ('application', '0002_auto_20210306_1709'),
        ('account', '0002_auto_20210306_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ad',
        ),
        migrations.AddField(
            model_name='profile',
            name='ad',
            field=models.ManyToManyField(to='ad.Ad'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='application',
        ),
        migrations.AddField(
            model_name='profile',
            name='application',
            field=models.ManyToManyField(to='application.Application'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='indication',
        ),
        migrations.AddField(
            model_name='profile',
            name='indication',
            field=models.ManyToManyField(to='meter.Indication'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='meter',
        ),
        migrations.AddField(
            model_name='profile',
            name='meter',
            field=models.ManyToManyField(to='meter.Meter'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reservation',
        ),
        migrations.AddField(
            model_name='profile',
            name='reservation',
            field=models.ManyToManyField(to='reservation.Reservation'),
        ),
    ]
