# Generated by Django 3.1.7 on 2021-03-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0003_auto_20210308_0933'),
        ('account', '0004_auto_20210308_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='indication',
        ),
        migrations.AddField(
            model_name='profile',
            name='indication',
            field=models.ManyToManyField(blank=True, null=True, to='meter.Indication'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='meter',
        ),
        migrations.AddField(
            model_name='profile',
            name='meter',
            field=models.ManyToManyField(blank=True, null=True, to='meter.Meter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.status'),
        ),
    ]
