# Generated by Django 3.1.7 on 2021-03-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0003_auto_20210308_0933'),
        ('account', '0005_auto_20210308_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='indication',
            field=models.ManyToManyField(blank=True, to='meter.Indication'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meter',
            field=models.ManyToManyField(blank=True, to='meter.Meter'),
        ),
    ]
