# Generated by Django 3.1.7 on 2021-03-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210308_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='indication',
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.status'),
        ),
    ]
