# Generated by Django 3.1.7 on 2021-03-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210308_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='meter',
        ),
    ]
