# Generated by Django 3.1.7 on 2021-03-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Санкт-Петербург', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='flat',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Невский', max_length=100),
        ),
    ]
