# Generated by Django 3.1.7 on 2021-03-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210308_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Площадъ квартиры'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Блокировка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban_end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец блокировки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало блокировки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Санкт-Петербург', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Невский', max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
