# Generated by Django 3.1.7 on 2021-03-09 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='accrued',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='sum',
            field=models.SmallIntegerField(default=0, verbose_name='Оплачено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Accrued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrued', models.SmallIntegerField(verbose_name='Начислено')),
                ('payment', models.BooleanField(default=False, verbose_name='Оплата')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['-created'],
            },
        ),
    ]
