# Generated by Django 3.1.7 on 2021-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20210306_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ending',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
