# Generated by Django 3.1.7 on 2021-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_auto_20210308_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Электричество день',
                'verbose_name_plural': 'Электричество день',
            },
        ),
        migrations.CreateModel(
            name='ElectroNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Электричество ночь',
                'verbose_name_plural': 'Электричество ночь',
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Газ',
                'verbose_name_plural': 'Газ',
            },
        ),
        migrations.CreateModel(
            name='HotWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Горячая вода',
                'verbose_name_plural': 'Горячей воды',
            },
        ),
        migrations.RenameModel(
            old_name='Parameter',
            new_name='CoolWater',
        ),
        migrations.AlterModelOptions(
            name='coolwater',
            options={'verbose_name': 'Холодная вода', 'verbose_name_plural': 'Холодной воды'},
        ),
    ]
