# Generated by Django 3.1.7 on 2021-03-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_auto_20210308_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coolwater',
            options={'verbose_name': 'Холодная вода', 'verbose_name_plural': 'Холодная вода'},
        ),
        migrations.AlterModelOptions(
            name='hotwater',
            options={'verbose_name': 'Горячая вода', 'verbose_name_plural': 'Горячая вода'},
        ),
        migrations.AlterField(
            model_name='coolwater',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='electroday',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='electronight',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gas',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='hotwater',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
