# Generated by Django 3.1.7 on 2021-03-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0004_auto_20210308_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='coolwater',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.parametertype'),
        ),
        migrations.AlterField(
            model_name='electroday',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.parametertype'),
        ),
        migrations.AlterField(
            model_name='electronight',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.parametertype'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.parametertype'),
        ),
        migrations.AlterField(
            model_name='hotwater',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.parametertype'),
        ),
    ]
