# Generated by Django 3.1.7 on 2021-03-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0005_auto_20210308_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolwater',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='electroday',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='electronight',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='gas',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='hotwater',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
