# Generated by Django 3.1.7 on 2021-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0006_auto_20210308_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolwater',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='electroday',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='electronight',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gas',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='hotwater',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
