# Generated by Django 3.1.7 on 2021-03-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0007_auto_20210308_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertype',
            name='slag',
            field=models.SlugField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
