# Generated by Django 3.1.7 on 2021-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0008_parametertype_slag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametertype',
            name='slag',
        ),
        migrations.AddField(
            model_name='parametertype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
