# Generated by Django 3.1.7 on 2021-03-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0010_auto_20210308_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametertype',
            options={'verbose_name': 'Тип параметра', 'verbose_name_plural': 'Типы параметров'},
        ),
    ]
