# Generated by Django 3.1.7 on 2021-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='data',
            new_name='due_data',
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
