# Generated by Django 3.1.7 on 2021-03-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-data_begin']},
        ),
    ]
