# Generated by Django 3.1.7 on 2021-03-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20210308_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-data_begin'], 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterModelOptions(
            name='typereservation',
            options={'verbose_name': 'Тип брони', 'verbose_name_plural': 'Типы броний'},
        ),
    ]
