# Generated by Django 3.1.7 on 2021-03-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_meter_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['name']},
        ),
    ]
