# Generated by Django 3.1.7 on 2021-03-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_meter'),
        ('meter', '0003_auto_20210308_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owen', to='account.profile')),
            ],
        ),
    ]
