# Generated by Django 3.1.7 on 2021-03-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_itemmeter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmeter',
            options={'verbose_name': 'User meter', 'verbose_name_plural': 'User meters'},
        ),
    ]
