# Generated by Django 3.1.7 on 2021-03-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0005_auto_20210308_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indication',
            options={'ordering': ['-created']},
        ),
    ]
