# Generated by Django 3.1.7 on 2021-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0006_auto_20210308_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='indication',
            name='used',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
