# Generated by Django 3.1.7 on 2021-03-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0007_indication_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indication',
            options={'ordering': ['-created'], 'verbose_name': 'Показание', 'verbose_name_plural': 'Покозания'},
        ),
        migrations.AlterModelOptions(
            name='itemmeter',
            options={'verbose_name': 'Владелец счетчика', 'verbose_name_plural': 'Владелецы счетчиков'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['name'], 'verbose_name': 'Счетчик', 'verbose_name_plural': 'Счетчики'},
        ),
        migrations.AlterModelOptions(
            name='typemeter',
            options={'verbose_name': 'Тип счетчика', 'verbose_name_plural': 'Типы счетчиков'},
        ),
    ]
